linters:
  enable:
    - errcheck
    - staticcheck
    - revive
    - govet
    - gosimple
    - unused
    - misspell
    - nilnil
    - gocritic
    - errname
    - cyclop

linters-settings:
  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]

  cyclop:
    # Maximum cyclomatic complexity per function.
    max-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - nilnil
