// Package outbox implements the Transactional Outbox pattern.
//
// Usage:
//  1. In the same transaction as your aggregate save, persist OutboxMessages via OutboxStore.Save.
//  2. Run OutboxPublisher to deliver those messages asynchronously.
//  3. OutboxPublisher guarantees at-least-once delivery via idempotent ID-based deduplication.
package outbox

import (
	"context"
	"sync"
	"time"
)

// OutboxMessage is a unit of work persisted alongside a domain aggregate.
// ID is the idempotency key — use a UUID generated by the caller.
// Payload must be JSON — serialization is the caller's responsibility.
type OutboxMessage struct {
	// ID is the idempotency key. Must be globally unique (e.g. UUID).
	ID          string
	AggregateID string
	EventType   string
	// Payload is JSON-encoded. The outbox is a delivery mechanism, not a serializer.
	Payload     []byte
	CreatedAt   time.Time
	ProcessedAt *time.Time
	// Attempts tracks how many delivery attempts have been made.
	Attempts int
}

// OutboxStore persists and queries outbox messages.
// Implement this interface backed by your application database.
type OutboxStore interface {
	// Save persists messages, typically in the same transaction as the aggregate.
	Save(ctx context.Context, msgs []OutboxMessage) error
	// FetchPending returns up to limit unprocessed messages.
	FetchPending(ctx context.Context, limit int) ([]OutboxMessage, error)
	// MarkProcessed marks a message as delivered. Idempotent — safe to call multiple times.
	MarkProcessed(ctx context.Context, id string) error
}

// PublishFunc is the function called to deliver a single outbox message.
type PublishFunc func(ctx context.Context, msg OutboxMessage) error

// publisherOptions holds resolved configuration for OutboxPublisher.
type publisherOptions struct {
	pollingInterval time.Duration
	batchSize       int
	concurrency     int
}

// Option configures an OutboxPublisher.
type Option func(*publisherOptions)

// WithPollingInterval sets how often the publisher polls for pending messages.
// Default: 5s.
func WithPollingInterval(d time.Duration) Option {
	return func(o *publisherOptions) { o.pollingInterval = d }
}

// WithBatchSize sets the maximum number of messages processed per polling cycle.
// Default: 100.
func WithBatchSize(n int) Option {
	return func(o *publisherOptions) { o.batchSize = n }
}

// WithConcurrency sets the number of concurrent delivery goroutines.
// Default: 1 (sequential — preserves message ordering within a batch).
func WithConcurrency(n int) Option {
	return func(o *publisherOptions) { o.concurrency = n }
}

// OutboxPublisher polls the OutboxStore and delivers pending messages via PublishFunc.
type OutboxPublisher struct {
	store   OutboxStore
	publish PublishFunc
	opts    publisherOptions
	stopCh  chan struct{}
	doneCh  chan struct{}
	once    sync.Once
}

// NewPublisher creates an OutboxPublisher with the given store and publish function.
func NewPublisher(store OutboxStore, publish PublishFunc, opts ...Option) *OutboxPublisher {
	o := publisherOptions{
		pollingInterval: 5 * time.Second,
		batchSize:       100,
		concurrency:     1,
	}
	for _, opt := range opts {
		opt(&o)
	}
	return &OutboxPublisher{
		store:   store,
		publish: publish,
		opts:    o,
		stopCh:  make(chan struct{}),
		doneCh:  make(chan struct{}),
	}
}

// Start launches the polling goroutine. Non-blocking — returns immediately.
// Returns an error if the publisher is already running.
// Cancel ctx or call Stop to gracefully shut down.
func (p *OutboxPublisher) Start(ctx context.Context) error {
	started := false
	p.once.Do(func() {
		started = true
		go p.run(ctx)
	})
	if !started {
		return nil // already running — idempotent
	}
	return nil
}

// Stop waits for the current polling cycle to complete before returning.
// ctx defines the maximum wait time for graceful shutdown.
func (p *OutboxPublisher) Stop(ctx context.Context) error {
	close(p.stopCh)
	select {
	case <-p.doneCh:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}

func (p *OutboxPublisher) run(ctx context.Context) {
	defer close(p.doneCh)
	ticker := time.NewTicker(p.opts.pollingInterval)
	defer ticker.Stop()

	for {
		select {
		case <-p.stopCh:
			return
		case <-ctx.Done():
			return
		case <-ticker.C:
			p.processOnce(ctx)
		}
	}
}

func (p *OutboxPublisher) processOnce(ctx context.Context) {
	msgs, err := p.store.FetchPending(ctx, p.opts.batchSize)
	if err != nil || len(msgs) == 0 {
		return
	}
	for _, msg := range msgs {
		if err := p.publish(ctx, msg); err != nil {
			continue // leave unprocessed for next cycle
		}
		_ = p.store.MarkProcessed(ctx, msg.ID)
	}
}
