// Package outbox implements the Transactional Outbox pattern.
//
// Usage:
//  1. In the same transaction as your aggregate save, persist OutboxMessages via Store.Save.
//  2. Run Publisher to deliver those messages asynchronously.
//  3. Publisher guarantees at-least-once delivery via idempotent ID-based deduplication.
package outbox

import (
	"context"
	"sync"
	"time"

	obs "github.com/marcusPrado02/go-commons/ports/observability"
)

// Message is a unit of work persisted alongside a domain aggregate.
// ID is the idempotency key — use a UUID generated by the caller.
// Payload must be JSON — serialization is the caller's responsibility.
type Message struct {
	// ID is the idempotency key. Must be globally unique (e.g. UUID).
	ID          string
	AggregateID string
	EventType   string
	// Payload is JSON-encoded. The outbox is a delivery mechanism, not a serializer.
	Payload     []byte
	CreatedAt   time.Time
	ProcessedAt *time.Time
	// Attempts tracks how many delivery attempts have been made.
	Attempts int
}

// Store persists and queries outbox messages.
// Implement this interface backed by your application database.
type Store interface {
	// Save persists messages, typically in the same transaction as the aggregate.
	Save(ctx context.Context, msgs []Message) error
	// FetchPending returns up to limit unprocessed messages.
	FetchPending(ctx context.Context, limit int) ([]Message, error)
	// MarkProcessed marks a message as delivered. Idempotent — safe to call multiple times.
	MarkProcessed(ctx context.Context, id string) error
}

// PublishFunc is the function called to deliver a single outbox message.
type PublishFunc func(ctx context.Context, msg Message) error

// publisherOptions holds resolved configuration for Publisher.
type publisherOptions struct {
	pollingInterval time.Duration
	batchSize       int
	concurrency     int
	logger          obs.Logger
}

// Option configures an Publisher.
type Option func(*publisherOptions)

// WithPollingInterval sets how often the publisher polls for pending messages.
// Default: 5s.
func WithPollingInterval(d time.Duration) Option {
	return func(o *publisherOptions) { o.pollingInterval = d }
}

// WithBatchSize sets the maximum number of messages processed per polling cycle.
// Default: 100.
func WithBatchSize(n int) Option {
	return func(o *publisherOptions) { o.batchSize = n }
}

// WithConcurrency sets the number of concurrent delivery goroutines.
// Default: 1 (sequential — preserves message ordering within a batch).
func WithConcurrency(n int) Option {
	return func(o *publisherOptions) { o.concurrency = n }
}

// WithLogger sets a structured logger for delivery errors and lifecycle events.
// If not set, errors are silently ignored (callers rely on dead-letter monitoring).
func WithLogger(l obs.Logger) Option {
	return func(o *publisherOptions) { o.logger = l }
}

// Publisher polls the Store and delivers pending messages via PublishFunc.
type Publisher struct {
	store   Store
	publish PublishFunc
	opts    publisherOptions
	stopCh  chan struct{}
	doneCh  chan struct{}
	once    sync.Once
}

// NewPublisher creates an Publisher with the given store and publish function.
// Panics if store or publish are nil.
func NewPublisher(store Store, publish PublishFunc, opts ...Option) *Publisher {
	if store == nil {
		panic("outbox: store must not be nil")
	}
	if publish == nil {
		panic("outbox: publish function must not be nil")
	}
	o := publisherOptions{
		pollingInterval: 5 * time.Second,
		batchSize:       100,
		concurrency:     1,
	}
	for _, opt := range opts {
		opt(&o)
	}
	return &Publisher{
		store:   store,
		publish: publish,
		opts:    o,
		stopCh:  make(chan struct{}),
		doneCh:  make(chan struct{}),
	}
}

// Start launches the polling goroutine. Non-blocking — returns immediately.
// Returns an error if the publisher is already running.
// Cancel ctx or call Stop to gracefully shut down.
func (p *Publisher) Start(ctx context.Context) error {
	started := false
	p.once.Do(func() {
		started = true
		go p.run(ctx)
	})
	if !started {
		return nil // already running — idempotent
	}
	return nil
}

// Stop waits for the current polling cycle to complete before returning.
// ctx defines the maximum wait time for graceful shutdown.
func (p *Publisher) Stop(ctx context.Context) error {
	close(p.stopCh)
	select {
	case <-p.doneCh:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}

func (p *Publisher) run(ctx context.Context) {
	defer close(p.doneCh)
	ticker := time.NewTicker(p.opts.pollingInterval)
	defer ticker.Stop()

	for {
		select {
		case <-p.stopCh:
			return
		case <-ctx.Done():
			return
		case <-ticker.C:
			p.processOnce(ctx)
		}
	}
}

func (p *Publisher) processOnce(ctx context.Context) {
	msgs, err := p.store.FetchPending(ctx, p.opts.batchSize)
	if err != nil {
		if p.opts.logger != nil {
			p.opts.logger.Error(ctx, "outbox: fetch pending failed", obs.Err(err))
		}
		return
	}
	if len(msgs) == 0 {
		return
	}
	for _, msg := range msgs {
		if err := p.publish(ctx, msg); err != nil {
			if p.opts.logger != nil {
				p.opts.logger.Error(ctx, "outbox: publish failed", obs.F("message_id", msg.ID), obs.Err(err))
			}
			continue // leave unprocessed for next cycle
		}
		if err := p.store.MarkProcessed(ctx, msg.ID); err != nil {
			if p.opts.logger != nil {
				p.opts.logger.Error(ctx, "outbox: mark processed failed", obs.F("message_id", msg.ID), obs.Err(err))
			}
		}
	}
}
